//! Client-encrypted `--config` layers.
//!
//! A config service stores ciphertext it cannot read: the secret is minted by
//! the publisher — in a browser, or by whatever tool wrote the config — and
//! never reaches the service in any form. A gateway pointed at such an address
//! fetches the payload over an ordinary unauthenticated `GET` (confidentiality
//! is the ciphertext's job, not the endpoint's) and opens it here.
//!
//! The `mcpg-config-v1` construction, which this file implements and
//! `apps/cloud/config/src/aad.rs` implements on the other side:
//!
//! ```text
//! secret  32 random bytes, written as `mcpg_sk_` + 52 Crockford base32 chars
//! key     HKDF-SHA256(ikm = secret, salt = kdf_salt, info = "mcpg-config-v1/key")
//! aad     "mcpg-config-v1|{id}|{version}|{expires_at}|{one_time}|{kdf_salt}"
//! ct      AES-256-GCM(key, nonce[12], aad, plaintext) || tag[16]
//! ```
//!
//! The secret is not the key. Three values come out of the same HKDF with three
//! different labels — the AES key, an edit token, and a burn receipt — and the
//! service is handed only SHA-256 digests of the last two. A value the service
//! has seen must not be the value that decrypts.
//!
//! Everything a reader acts on is inside the tag: `id` stops a blob being
//! transplanted onto another config, `version` stops one being replayed under a
//! different number, and `expires_at`, `one_time` and `kdf_salt` stop the host
//! rewriting the terms of a config it cannot read. **The id used to build that
//! string is the one in the URL that was fetched, never the one in the
//! response** — trusting the response would let a host answer a request for one
//! config with another config's authentic blob, pick that config's key out of
//! the operator's key map, and boot it while the audit trail named the address
//! that was asked for.
//!
//! The plaintext is a JSON envelope rather than raw YAML because the config's
//! name has to be hidden from the service too, and the only place to hide it is
//! inside the ciphertext.
//!
//! Keeping two implementations of one construction in step is what
//! `src/config/testdata/config-enc-v1-vector.json` is for: a vector generated by the
//! browser code, decrypted here.

use std::collections::BTreeMap;
use std::io::{IsTerminal as _, Write as _};
use std::path::{Path, PathBuf};
use std::sync::OnceLock;

use aes_gcm::aead::{Aead, KeyInit, Payload};
use aes_gcm::{Aes256Gcm, Nonce};
use anyhow::{Context as _, Result, bail};
use base64::Engine as _;
use base64::engine::general_purpose::{STANDARD as B64, URL_SAFE_NO_PAD};
use mcpg_sensitive::Sensitive;
use serde::Deserialize;
use zeroize::Zeroize as _;

/// The scheme that marks a `--config` value as a client-encrypted address. It
/// is the whole signal — no content-type sniffing, no body probing — because
/// the alternative is guessing, and a guess that lands wrong surfaces much
/// later as an unexplained YAML parse error.
pub const SCHEME: &str = "mcpg+enc:";

/// Names the construction: key derivation, AEAD, and the AAD field tuple
/// together. It is the first token of the AAD, so it is inside the tag.
pub const CONSTRUCTION: &str = "mcpg-config-v1";
/// HKDF label for the AES key. The other two labels belong to values only a
/// publisher or an editor produces, so the gateway has no use for them.
const INFO_KEY: &str = "mcpg-config-v1/key";
/// The only key derivation this gateway opens. A passphrase-derived config
/// (`pbkdf2-sha256`) is refused by name rather than attempted.
const KDF_HKDF: &str = "hkdf-sha256";

/// Marker on the JSON document inside the ciphertext.
pub const PLAINTEXT_DOC: &str = "mcpg.config/v1";
/// The only plaintext encoding this construction defines.
pub const PLAINTEXT_FORMAT: &str = "yaml";

/// Human-facing prefix on the secret. Not key material — stripped before
/// decoding. It exists so secret scanners have a rule to match, so an error can
/// say "that is not a config secret" instead of "decryption failed", and so a
/// secret is recognisable in a paste.
pub const SECRET_PREFIX: &str = "mcpg_sk_";
/// Crockford base32 minus `i`, `l`, `o`, `u`: no glyph a human can transcribe
/// two ways.
const CROCKFORD: &[u8; 32] = b"0123456789abcdefghjkmnpqrstvwxyz";
/// 32 bytes at 5 bits a character.
const SECRET_BODY_CHARS: usize = 52;
const SECRET_BYTES: usize = 32;
/// 16 bytes at 5 bits a character. 128 random bits, so ids cannot be walked.
const ID_CHARS: usize = 26;
const NONCE_BYTES: usize = 12;
const TAG_BYTES: usize = 16;
const SALT_BYTES: usize = 16;
/// Cap on the decrypted document. A gateway config is a few KiB.
const MAX_PLAINTEXT_BYTES: usize = 1024 * 1024;

/// Holds one secret, read from a file so a Kubernetes Secret can mount it.
/// The documented preference: an environment variable is readable through
/// `/proc/<pid>/environ` for the life of the process and lands in core dumps,
/// and this gateway does not try to hide it afterwards — unsetting a variable
/// while other threads may be reading the environment is undefined behaviour,
/// and a documented exposure beats one papered over with a data race.
pub const SECRET_FILE_ENV: &str = "MCPG_CONFIG_SECRET_FILE";
/// Holds one secret inline. See [`SECRET_FILE_ENV`] for why that is preferred.
pub const SECRET_ENV: &str = "MCPG_CONFIG_SECRET";
/// Path to a `{"<id>": "mcpg_sk_…"}` JSON map, for a boot with several
/// encrypted layers. Resolves *which* secret applies to *which* layer
/// explicitly rather than trying every secret against every blob.
pub const SECRETS_FILE_ENV: &str = "MCPG_CONFIG_SECRETS_FILE";
/// Refuse any encrypted layer published below this version. A partial defence
/// against a host that answers "latest" with an older but genuinely authentic
/// version; the pinned `/v/<n>` address is the complete one.
pub const MIN_VERSION_ENV: &str = "MCPG_CONFIG_MIN_VERSION";

/// Why an encrypted layer could not be turned into YAML. The variants are
/// separate because the operator's next move differs: fix the secret, ask the
/// publisher to re-publish, or report a broken payload.
#[derive(Debug)]
pub enum DecryptFailure {
    /// The secret, the payload, or the decrypted document is not the shape
    /// `mcpg-config-v1` defines. Nothing was decrypted.
    Malformed(String),
    /// AES-GCM authentication failed.
    WrongSecret { id: String },
    /// The authenticated expiry is in the past.
    Expired { id: String, expires_at: i64 },
}

impl std::fmt::Display for DecryptFailure {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Malformed(detail) => write!(f, "malformed encrypted config: {detail}"),
            Self::WrongSecret { id } => write!(
                f,
                "wrong config secret for {id}: AES-GCM authentication failed. The secret, the \
                 config id, the version, the expiry and the one-time flag are authenticated \
                 together, so a secret minted for a different config fails here too. Check the \
                 value you supplied via {SECRET_FILE_ENV} / {SECRET_ENV} / {SECRETS_FILE_ENV} / \
                 `#k=`."
            ),
            Self::Expired { id, expires_at } => write!(
                f,
                "config {id} expired at unix {expires_at}. The expiry is authenticated, so only \
                 the secret holder can change it — re-publish the config with a new expiry."
            ),
        }
    }
}

impl std::error::Error for DecryptFailure {}

fn malformed(detail: impl Into<String>) -> DecryptFailure {
    DecryptFailure::Malformed(detail.into())
}

/// The 32 secret bytes, wiped on drop. `Debug` renders nothing, so the secret
/// cannot reach a log through `tracing::info!(?x)` or a panic message.
pub struct ConfigSecret {
    bytes: [u8; SECRET_BYTES],
}

impl std::fmt::Debug for ConfigSecret {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("ConfigSecret(***)")
    }
}

impl Drop for ConfigSecret {
    fn drop(&mut self) {
        self.bytes.zeroize();
    }
}

/// Parse the presentation form: `mcpg_sk_` + 52 Crockford base32 characters.
///
/// The prefix is optional on input and stripped before decoding — it is a
/// recognition aid, not key material, so both spellings decode to the same
/// bytes. Whitespace goes first, because a secret arrives through a password
/// manager or a wrapped email as often as through a clean paste.
pub fn parse_secret(raw: &str) -> Result<ConfigSecret, DecryptFailure> {
    let compact: String = raw
        .chars()
        .filter(|c| !c.is_whitespace())
        .flat_map(char::to_lowercase)
        .collect();
    let body = compact.strip_prefix(SECRET_PREFIX).unwrap_or(&compact);
    if body.len() != SECRET_BODY_CHARS {
        return Err(malformed(format!(
            "a config secret is `{SECRET_PREFIX}` and {SECRET_BODY_CHARS} characters; this one \
             has {} characters after the prefix",
            body.len()
        )));
    }
    let mut decoded = decode_crockford(body)?;
    if decoded.len() < SECRET_BYTES {
        decoded.zeroize();
        return Err(malformed("a config secret decodes to 32 bytes"));
    }
    let mut bytes = [0u8; SECRET_BYTES];
    bytes.copy_from_slice(&decoded[..SECRET_BYTES]);
    decoded.zeroize();
    Ok(ConfigSecret { bytes })
}

/// Crockford base32, most-significant bit first, no padding — the mirror of the
/// publisher's encoder. A trailing partial group is dropped, exactly as the
/// encoder's leftover bits were padding rather than data.
fn decode_crockford(text: &str) -> Result<Vec<u8>, DecryptFailure> {
    let mut bits = 0u32;
    let mut value = 0u32;
    let mut out = Vec::with_capacity(text.len() * 5 / 8);
    for ch in text.bytes() {
        let Some(idx) = CROCKFORD.iter().position(|c| *c == ch) else {
            return Err(malformed(format!(
                "a config secret is Crockford base32 ({}); `{}` is not in that alphabet",
                String::from_utf8_lossy(CROCKFORD),
                ch as char
            )));
        };
        value = (value << 5) | idx as u32;
        bits += 5;
        if bits >= 8 {
            out.push(((value >> (bits - 8)) & 0xff) as u8);
            bits -= 8;
        }
    }
    Ok(out)
}

/// Whether a string is shaped like a config id: 26 Crockford base32 characters.
#[must_use]
pub fn is_config_id(value: &str) -> bool {
    value.len() == ID_CHARS && value.bytes().all(|b| CROCKFORD.contains(&b))
}

/// The exact byte string the tag covers. Only ever constructed, never parsed.
///
/// The other implementation is `apps/cloud/config/src/aad.rs`; the golden
/// vector test is what keeps them byte-identical.
#[must_use]
pub fn aad(
    id: &str,
    version: u64,
    expires_at: i64,
    one_time_read: bool,
    kdf_salt: &[u8],
) -> String {
    format!(
        "{CONSTRUCTION}|{id}|{version}|{expires_at}|{}|{}",
        u8::from(one_time_read),
        URL_SAFE_NO_PAD.encode(kdf_salt)
    )
}

/// One encrypted payload, as fetched. Every field but `id` comes off the wire;
/// `id` is the one the gateway asked for, and that asymmetry is the point.
#[derive(Debug)]
pub struct EncryptedPayload {
    /// From the URL, never from the response.
    pub id: String,
    pub version: u64,
    /// Unix seconds UTC.
    pub expires_at: i64,
    pub one_time_read: bool,
    pub kdf: String,
    pub kdf_salt: Vec<u8>,
    pub nonce: Vec<u8>,
    /// Ciphertext with the 16-byte tag appended.
    pub ciphertext: Vec<u8>,
    /// What the host says the associated data is. Diagnostic only: the value
    /// actually used is rebuilt locally, and a disagreement is a named error.
    pub served_aad: Option<String>,
}

impl EncryptedPayload {
    fn check_shape(&self) -> Result<(), DecryptFailure> {
        if !is_config_id(&self.id) {
            return Err(malformed(format!(
                "`{}` is not a config id: {ID_CHARS} Crockford base32 characters",
                self.id
            )));
        }
        if self.kdf != KDF_HKDF {
            return Err(malformed(format!(
                "this config was published with `{}`; the gateway opens `{KDF_HKDF}` configs \
                 only. A passphrase-derived config has to be decrypted where the passphrase is.",
                self.kdf
            )));
        }
        if self.version < 1 {
            return Err(malformed("a config version starts at 1"));
        }
        if self.kdf_salt.len() != SALT_BYTES {
            return Err(malformed(format!(
                "`kdf_salt` is {} bytes, this construction uses {SALT_BYTES}",
                self.kdf_salt.len()
            )));
        }
        if self.nonce.len() != NONCE_BYTES {
            return Err(malformed(format!(
                "`nonce` is {} bytes, AES-GCM takes {NONCE_BYTES}",
                self.nonce.len()
            )));
        }
        if self.ciphertext.len() <= TAG_BYTES {
            return Err(malformed(format!(
                "the payload is {} bytes, which cannot hold a {TAG_BYTES}-byte tag and a document",
                self.ciphertext.len()
            )));
        }
        if self.ciphertext.len() - TAG_BYTES > MAX_PLAINTEXT_BYTES {
            return Err(malformed(format!(
                "the decrypted document would be {} bytes, over the {MAX_PLAINTEXT_BYTES}-byte cap",
                self.ciphertext.len() - TAG_BYTES
            )));
        }
        Ok(())
    }

    /// The associated data this gateway will authenticate against — built from
    /// the id it asked for, never the id it was told.
    #[must_use]
    pub fn aad(&self) -> String {
        aad(
            &self.id,
            self.version,
            self.expires_at,
            self.one_time_read,
            &self.kdf_salt,
        )
    }
}

/// The JSON document inside the ciphertext. Advisory display metadata is
/// optional and unknown keys are tolerated: this side of the tag is written by
/// whoever holds the secret, and a new display field must not break an old
/// gateway.
#[derive(Debug, Deserialize)]
struct PlaintextEnvelope {
    doc: String,
    format: String,
    config: String,
    #[serde(default)]
    name: Option<String>,
}

/// A decrypted layer. `name` is advisory — it never reaches the origin label.
#[derive(Debug)]
pub struct DecryptedConfig {
    pub id: String,
    pub version: u64,
    pub name: Option<String>,
    pub yaml: String,
}

/// Derive the AES-256-GCM key. RFC 5869 with the construction's own label, so a
/// secret cannot be replayed as any other secret-derived value.
fn derive_cipher(secret: &ConfigSecret, salt: &[u8]) -> Result<Aes256Gcm, DecryptFailure> {
    let hk = hkdf::Hkdf::<sha2::Sha256>::new(Some(salt), &secret.bytes);
    let mut key = [0u8; 32];
    hk.expand(INFO_KEY.as_bytes(), &mut key)
        .map_err(|_| malformed("key derivation produced the wrong length"))?;
    let cipher = Aes256Gcm::new_from_slice(&key)
        .map_err(|_| malformed("derived key is not a valid AES-256 key"));
    key.zeroize();
    cipher
}

/// Open one payload. `now_unix` is a parameter so the expiry check is testable
/// without waiting for a clock.
pub fn open(
    payload: &EncryptedPayload,
    secret: &ConfigSecret,
    now_unix: i64,
) -> Result<DecryptedConfig, DecryptFailure> {
    payload.check_shape()?;

    // Rebuilt locally, then compared. The comparison buys a straight answer
    // rather than a security property: both strings are ours to compute, so a
    // host running a different construction gets named as such instead of
    // presenting as a wrong secret.
    let aad = payload.aad();
    if let Some(served) = &payload.served_aad
        && served != &aad
    {
        return Err(malformed(format!(
            "the host says this config is bound to {served:?}, but the address and parameters it \
             served describe {aad:?} — it is running a different construction"
        )));
    }

    let cipher = derive_cipher(secret, &payload.kdf_salt)?;
    let plaintext = cipher
        .decrypt(
            Nonce::from_slice(&payload.nonce),
            Payload {
                msg: &payload.ciphertext,
                aad: aad.as_bytes(),
            },
        )
        .map_err(|_| DecryptFailure::WrongSecret {
            id: payload.id.clone(),
        })?;
    if plaintext.len() > MAX_PLAINTEXT_BYTES {
        return Err(malformed(format!(
            "decrypted document is {} bytes, over the {MAX_PLAINTEXT_BYTES}-byte cap",
            plaintext.len()
        )));
    }

    let inner: PlaintextEnvelope = serde_json::from_slice(&plaintext).map_err(|e| {
        malformed(format!(
            "decrypted document is not `{PLAINTEXT_DOC}` JSON: {e}"
        ))
    })?;
    if inner.doc != PLAINTEXT_DOC {
        return Err(malformed(format!(
            "decrypted `doc` is {:?}, expected {PLAINTEXT_DOC:?}",
            inner.doc
        )));
    }
    if inner.format != PLAINTEXT_FORMAT {
        return Err(malformed(format!(
            "decrypted `format` is {:?}, this gateway reads {PLAINTEXT_FORMAT:?}",
            inner.format
        )));
    }

    // Checked after decryption: the host's own expiry sweep is housekeeping,
    // and the authenticated value is the boundary.
    if payload.expires_at != 0 && payload.expires_at <= now_unix {
        return Err(DecryptFailure::Expired {
            id: payload.id.clone(),
            expires_at: payload.expires_at,
        });
    }

    Ok(DecryptedConfig {
        id: payload.id.clone(),
        version: payload.version,
        name: inner.name,
        yaml: inner.config,
    })
}

/// Decode one of the payload route's base64 parameters. Standard alphabet with
/// padding, which is what the service emits.
pub fn decode_b64(field: &str, value: &str) -> Result<Vec<u8>, DecryptFailure> {
    B64.decode(value.trim())
        .map_err(|e| malformed(format!("`{field}` is not standard base64: {e}")))
}

/// The downgrade floor from [`MIN_VERSION_ENV`], if the operator set one.
pub fn min_version() -> Result<Option<u64>> {
    let Some(raw) = std::env::var_os(MIN_VERSION_ENV) else {
        return Ok(None);
    };
    let raw = raw.to_string_lossy();
    let trimmed = raw.trim();
    if trimmed.is_empty() {
        return Ok(None);
    }
    let parsed: u64 = trimmed
        .parse()
        .with_context(|| format!("{MIN_VERSION_ENV} must be a version number, got {trimmed:?}"))?;
    Ok(Some(parsed))
}

// ---------------------------------------------------------------------------
// Addresses
// ---------------------------------------------------------------------------

/// Where to fetch a payload from, and which config it is.
#[derive(Debug, PartialEq, Eq)]
pub struct Address {
    /// The URL to `GET`.
    pub fetch_url: String,
    pub id: String,
    /// Set when the operator pinned a version. A pinned fetch is the complete
    /// defence against a host that answers "latest" with an older blob.
    pub version: Option<u64>,
}

/// Turn the address an operator pastes into the route that serves bytes.
///
/// Both shapes are accepted because both are handed out: the receipt prints the
/// human `/c/<id>` page, and the publish response also names the machine route
/// for a caller that speaks HTTP directly. Anything else is refused by name
/// rather than fetched hopefully — a wrong path answers `200 text/html` on most
/// hosts, and that would arrive as an unexplained YAML parse error.
pub fn parse_address(url: &str) -> Result<Address> {
    let (without_query, _) = url.split_once('?').unwrap_or((url, ""));
    let trimmed = without_query.trim_end_matches('/');
    let (origin, path) = split_origin(trimmed)?;
    let seg: Vec<&str> = path.split('/').filter(|s| !s.is_empty()).collect();

    let (id, version, prefix): (&str, Option<u64>, &[&str]) = match seg.as_slice() {
        // https://host/c/<id>
        [.., "c", id] => (id, None, &seg[..seg.len() - 2]),
        // https://host/c/<id>/v/<n>
        [.., "c", id, "v", n] => (id, Some(parse_version(n)?), &seg[..seg.len() - 4]),
        // https://host/v1/configs/<id>/ciphertext
        [.., "v1", "configs", id, "ciphertext"] => (id, None, &seg[..seg.len() - 4]),
        // https://host/v1/configs/<id>/versions/<n>/ciphertext
        [.., "v1", "configs", id, "versions", n, "ciphertext"] => {
            (id, Some(parse_version(n)?), &seg[..seg.len() - 6])
        }
        _ => bail!(
            "`{url}` is not a config address. Expected `<host>/c/<id>` (optionally `/v/<n>` to \
             pin a version), or the payload route `<host>/v1/configs/<id>/ciphertext`."
        ),
    };
    if !is_config_id(id) {
        bail!(
            "`{id}` is not a config id: {ID_CHARS} Crockford base32 characters \
             (`0123456789abcdefghjkmnpqrstvwxyz`). A truncated address looks exactly like this."
        );
    }

    let base = if prefix.is_empty() {
        origin.to_owned()
    } else {
        format!("{origin}/{}", prefix.join("/"))
    };
    let fetch_url = match version {
        Some(n) => format!("{base}/v1/configs/{id}/versions/{n}/ciphertext"),
        None => format!("{base}/v1/configs/{id}/ciphertext"),
    };
    Ok(Address {
        fetch_url,
        id: id.to_owned(),
        version,
    })
}

fn parse_version(raw: &str) -> Result<u64> {
    let n: u64 = raw
        .parse()
        .with_context(|| format!("`{raw}` is not a config version"))?;
    if n < 1 {
        bail!("config versions start at 1, not {n}");
    }
    Ok(n)
}

/// Split `scheme://host[:port]` off the path, keeping any path prefix the
/// deployment sits under.
fn split_origin(url: &str) -> Result<(&str, &str)> {
    let after_scheme = url
        .find("://")
        .map(|i| i + 3)
        .context("a config address needs an https:// or http:// scheme")?;
    match url[after_scheme..].find('/') {
        Some(i) => Ok(url.split_at(after_scheme + i)),
        None => Ok((url, "")),
    }
}

// ---------------------------------------------------------------------------
// Where the secret comes from
// ---------------------------------------------------------------------------

/// Split a `#k=…` fragment off a `--config` value, returning the URL to fetch
/// and the secret it carried. Grammar: `&`-separated params split on the FIRST
/// `=`; only `k` is defined, unknown params are ignored, and a bare `#anchor`
/// with no `=` is not key material — an ordinary anchor must never be mistaken
/// for a secret. The fragment is removed before anything else touches the
/// value, so it cannot reach `origin_label()` and the audit trail.
#[must_use]
pub fn split_fragment(spec: &str) -> (&str, Option<Sensitive<String>>) {
    let Some((url, fragment)) = spec.split_once('#') else {
        return (spec, None);
    };
    let key = fragment.split('&').find_map(|param| {
        let (name, value) = param.split_once('=')?;
        (name == "k").then(|| Sensitive::new(value.to_owned()))
    });
    (url, key)
}

/// The same value with any `k` fragment param masked, for the one place a
/// `--config` spec is echoed verbatim: the error context wrapping a failed
/// layer. An operator pastes the whole share link often enough that the naive
/// `format!("--config {spec}")` would print the secret on any boot failure.
#[must_use]
pub fn redacted_spec(spec: &str) -> String {
    let Some((url, fragment)) = spec.split_once('#') else {
        return spec.to_owned();
    };
    let masked: Vec<String> = fragment
        .split('&')
        .map(|param| match param.split_once('=') {
            Some(("k", _)) => "k=***".to_owned(),
            _ => param.to_owned(),
        })
        .collect();
    format!("{url}#{}", masked.join("&"))
}

/// Find the secret for one encrypted layer. First hit wins, and a miss is a
/// hard error naming the id — never a silent skip and never a plaintext
/// fallthrough.
pub fn resolve_secret(id: &str, fragment: Option<&Sensitive<String>>) -> Result<ConfigSecret> {
    let candidate = if let Some(from_fragment) = fragment {
        from_fragment.clone()
    } else if let Some(from_map) = secret_from_secrets_file(id)? {
        from_map
    } else if let Some(from_env) = env_secret()? {
        from_env
    } else if let Some(typed) = prompt_for_secret(id)? {
        typed
    } else {
        bail!(
            "no config secret for {id}. Supply one of: `{SECRET_FILE_ENV}=<path to a file holding \
             {SECRET_PREFIX}…>` (preferred — a Kubernetes Secret mounts as a file, and an \
             environment variable is readable through /proc/<pid>/environ), \
             `{SECRET_ENV}={SECRET_PREFIX}…`, `{SECRETS_FILE_ENV}=<path to a 0600 JSON map of id \
             → secret>`, or a `#k={SECRET_PREFIX}…` fragment on the --config address."
        )
    };
    Ok(parse_secret(candidate.expose())?)
}

/// Cached because a later encrypted layer needs the same value and re-reading
/// a file per layer would be a second chance to fail halfway through a boot.
static ENV_SECRET: OnceLock<Result<Option<Sensitive<String>>, String>> = OnceLock::new();

fn env_secret() -> Result<Option<Sensitive<String>>> {
    ENV_SECRET
        .get_or_init(|| read_env_secret().map_err(|e| format!("{e:#}")))
        .clone()
        .map_err(|e| anyhow::anyhow!(e))
}

fn read_env_secret() -> Result<Option<Sensitive<String>>> {
    // No permission gate on this one: the documented deployment is a
    // Kubernetes Secret volume, which mounts world-readable by default, and
    // refusing to boot on the recommended shape would push operators back to
    // the env-var form this file exists to replace.
    let from_file = match std::env::var(SECRET_FILE_ENV) {
        Ok(raw) if !raw.trim().is_empty() => {
            let path = PathBuf::from(raw.trim());
            let text = std::fs::read_to_string(&path)
                .with_context(|| format!("{SECRET_FILE_ENV}: read {}", path.display()))?;
            Some(text.trim().to_owned())
        }
        _ => None,
    };
    let inline = std::env::var(SECRET_ENV)
        .ok()
        .map(|v| v.trim().to_owned())
        .filter(|v| !v.is_empty());
    reconcile_env_secret(from_file, inline)
}

/// The file form wins, but two DIFFERENT values are a contradiction rather
/// than a precedence question — the operator meant one of them.
fn reconcile_env_secret(
    from_file: Option<String>,
    inline: Option<String>,
) -> Result<Option<Sensitive<String>>> {
    match (from_file, inline) {
        (Some(file), Some(env)) if file != env => {
            bail!(
                "{SECRET_FILE_ENV} and {SECRET_ENV} are both set and hold different secrets — \
                 unset one"
            )
        }
        (Some(value), _) | (None, Some(value)) => Ok(Some(Sensitive::new(value))),
        (None, None) => Ok(None),
    }
}

fn secret_from_secrets_file(id: &str) -> Result<Option<Sensitive<String>>> {
    let Some(raw) = std::env::var_os(SECRETS_FILE_ENV) else {
        return Ok(None);
    };
    let path = PathBuf::from(raw);
    if path.as_os_str().is_empty() {
        return Ok(None);
    }
    enforce_owner_only(&path, SECRETS_FILE_ENV)?;
    let text = std::fs::read_to_string(&path)
        .with_context(|| format!("{SECRETS_FILE_ENV}: read {}", path.display()))?;
    let map: BTreeMap<String, String> = serde_json::from_str(&text).with_context(|| {
        format!(
            "{SECRETS_FILE_ENV} ({}) must be a JSON object of config id → secret",
            path.display()
        )
    })?;
    Ok(map
        .get(id)
        .map(|k| Sensitive::new(k.trim().to_owned()))
        .filter(|k| !k.expose().is_empty()))
}

/// A secret MAP is operator-authored on a workstation, so its permissions are
/// the operator's to get right — and a world-readable one hands over every
/// config at once.
#[cfg(unix)]
fn enforce_owner_only(path: &Path, var: &str) -> Result<()> {
    use std::os::unix::fs::PermissionsExt as _;
    let mode = std::fs::metadata(path)
        .with_context(|| format!("{var}: stat {}", path.display()))?
        .permissions()
        .mode();
    if mode & 0o077 != 0 {
        bail!(
            "{var} ({}) is mode {:04o}; a file holding config secrets must be readable by its \
             owner only — `chmod 600 {}`",
            path.display(),
            mode & 0o7777,
            path.display()
        );
    }
    Ok(())
}

#[cfg(not(unix))]
fn enforce_owner_only(_path: &Path, _var: &str) -> Result<()> {
    Ok(())
}

fn prompt_for_secret(id: &str) -> Result<Option<Sensitive<String>>> {
    if !std::io::stdin().is_terminal() {
        return Ok(None);
    }
    let mut err = std::io::stderr();
    write!(err, "config secret for {id} (input is hidden): ").ok();
    err.flush().ok();
    let typed = read_line_no_echo()?;
    writeln!(err).ok();
    let typed = typed.trim().to_owned();
    Ok((!typed.is_empty()).then(|| Sensitive::new(typed)))
}

#[cfg(unix)]
fn read_line_no_echo() -> Result<String> {
    use std::io::BufRead as _;

    let fd = libc::STDIN_FILENO;
    let mut term: libc::termios = unsafe { std::mem::zeroed() };
    // SAFETY: `fd` is stdin and known to be a terminal (checked by the caller);
    // `term` is a live, correctly sized `termios`.
    if unsafe { libc::tcgetattr(fd, &mut term) } != 0 {
        bail!("cannot read terminal settings to hide the config secret as it is typed");
    }
    let saved = term;
    term.c_lflag &= !libc::ECHO;
    // SAFETY: same fd, and `term` is the struct just filled by tcgetattr.
    if unsafe { libc::tcsetattr(fd, libc::TCSANOW, &term) } != 0 {
        bail!(
            "cannot turn terminal echo off; refusing to prompt for the config secret in the clear"
        );
    }
    let mut line = String::new();
    let read = std::io::stdin().lock().read_line(&mut line);
    // Restore before propagating: an error must not leave the terminal mute.
    // SAFETY: `saved` is the unmodified struct tcgetattr produced.
    unsafe {
        libc::tcsetattr(fd, libc::TCSANOW, &saved);
    }
    read.context("read the config secret from the terminal")?;
    Ok(line)
}

#[cfg(not(unix))]
fn read_line_no_echo() -> Result<String> {
    bail!(
        "hidden terminal input is not available on this platform — supply the secret via \
         {SECRET_FILE_ENV} or {SECRET_ENV}"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Render raw bytes the way a publisher does, so the tests exercise the
    /// presentation form rather than the parser's own inverse.
    fn secret_text(bytes: &[u8; SECRET_BYTES]) -> String {
        let mut bits = 0u32;
        let mut value = 0u32;
        let mut out = String::new();
        for b in bytes {
            value = (value << 8) | u32::from(*b);
            bits += 8;
            while bits >= 5 {
                out.push(CROCKFORD[((value >> (bits - 5)) & 31) as usize] as char);
                bits -= 5;
            }
        }
        if bits > 0 {
            out.push(CROCKFORD[((value << (5 - bits)) & 31) as usize] as char);
        }
        format!("{SECRET_PREFIX}{}", &out[..SECRET_BODY_CHARS])
    }

    fn raw(text: &str) -> [u8; SECRET_BYTES] {
        parse_secret(text).unwrap().bytes
    }

    #[test]
    fn a_secret_round_trips_through_the_presentation_form() {
        let bytes = [7u8; SECRET_BYTES];
        let text = secret_text(&bytes);
        assert_eq!(text.len(), SECRET_PREFIX.len() + SECRET_BODY_CHARS);
        assert_eq!(raw(&text), bytes);
        // The prefix is a recognition aid, not key material.
        assert_eq!(raw(text.strip_prefix(SECRET_PREFIX).unwrap()), bytes);
        // Whitespace a password manager or a wrapped email inserted.
        assert_eq!(raw(&format!("  {} \n", text.replace("77", "77 "))), bytes);
    }

    #[test]
    fn a_secret_of_the_wrong_shape_is_named_as_such_not_tried() {
        for bad in ["hunter2", "", &"z".repeat(51), &"z".repeat(53)] {
            let err = parse_secret(bad).unwrap_err().to_string();
            assert!(err.contains("config secret"), "{bad}: {err}");
        }
        // `i`, `l`, `o` and `u` are outside the alphabet on purpose.
        let err = parse_secret(&format!("{SECRET_PREFIX}{}", "i".repeat(52)))
            .unwrap_err()
            .to_string();
        assert!(err.contains("Crockford"), "{err}");
    }

    #[test]
    fn the_id_alphabet_rejects_a_truncated_or_ambiguous_address() {
        assert!(is_config_id("0k3n8xq2vftr7bdyw5m1jhpz6c"));
        assert!(!is_config_id("0k3n8xq2vftr7bdyw5m1jhpz6"));
        assert!(!is_config_id("0k3n8xq2vftr7bdyw5m1jhpz6C"));
        assert!(!is_config_id("../../etc/passwd"));
    }

    const ID: &str = "0k3n8xq2vftr7bdyw5m1jhpz6c";

    #[test]
    fn the_aad_is_the_construction_s_field_tuple() {
        assert_eq!(
            aad(ID, 3, 1_800_000_000, true, &[2u8; 16]),
            "mcpg-config-v1|0k3n8xq2vftr7bdyw5m1jhpz6c|3|1800000000|1|AgICAgICAgICAgICAgICAg"
        );
    }

    #[test]
    fn both_address_shapes_resolve_to_the_payload_route() {
        // The prefix-less shape, which is what a self-hosted deployment mints
        // and what every address published before the managed service moved to
        // `mcpg.cloud/configs` still says. Nothing in the construction binds a
        // host — the AAD is `id|version|expires_at|one_time|kdf_salt` — so these
        // keep decrypting for as long as the host keeps answering.
        let expected = format!("https://config.mcpg.cloud/v1/configs/{ID}/ciphertext");
        for input in [
            format!("https://config.mcpg.cloud/c/{ID}"),
            format!("https://config.mcpg.cloud/c/{ID}/"),
            format!("https://config.mcpg.cloud/v1/configs/{ID}/ciphertext"),
            format!("https://config.mcpg.cloud/c/{ID}?utm=x"),
        ] {
            let addr = parse_address(&input).unwrap();
            assert_eq!(addr.fetch_url, expected, "{input}");
            assert_eq!(addr.id, ID);
            assert_eq!(addr.version, None);
        }
    }

    #[test]
    fn a_pinned_address_carries_its_version_into_the_route() {
        let addr = parse_address(&format!("https://config.mcpg.cloud/c/{ID}/v/7")).unwrap();
        assert_eq!(
            addr.fetch_url,
            format!("https://config.mcpg.cloud/v1/configs/{ID}/versions/7/ciphertext")
        );
        assert_eq!(addr.version, Some(7));
    }

    #[test]
    fn a_deployment_under_a_path_prefix_keeps_it() {
        let addr = parse_address(&format!("https://example.test/configs/c/{ID}")).unwrap();
        assert_eq!(
            addr.fetch_url,
            format!("https://example.test/configs/v1/configs/{ID}/ciphertext")
        );
    }

    #[test]
    fn the_managed_service_s_own_coordinates_resolve() {
        // Pinned to the literal address the managed service hands out, not a
        // stand-in host: this is the one shape that arrives in the field in
        // volume, and the payload route it derives is what the edge has to be
        // routing. The generic case above proves the rule; this proves the
        // deployment agrees with it.
        let addr = parse_address(&format!("https://mcpg.cloud/configs/c/{ID}")).unwrap();
        assert_eq!(
            addr.fetch_url,
            format!("https://mcpg.cloud/configs/v1/configs/{ID}/ciphertext")
        );
        assert_eq!(addr.id, ID);
        assert_eq!(addr.version, None);
    }

    #[test]
    fn an_address_that_is_not_a_config_address_is_refused_by_name() {
        // A bare origin, an unknown path, and a truncated id each get a message
        // naming what was expected — the alternative is a hopeful GET that
        // answers 200 text/html and fails much later as a YAML parse error.
        for bad in [
            "https://config.mcpg.cloud/".to_owned(),
            "https://config.mcpg.cloud/download".to_owned(),
            format!("https://config.mcpg.cloud/c/{}", &ID[..25]),
            format!("/c/{ID}"),
        ] {
            assert!(parse_address(&bad).is_err(), "{bad} should be refused");
        }
    }

    #[test]
    fn fragment_yields_only_a_k_param() {
        let (url, key) = split_fragment("mcpg+enc:https://c.example/c/abc#k=mcpg_sk_xyz");
        assert_eq!(url, "mcpg+enc:https://c.example/c/abc");
        assert_eq!(key.unwrap().expose(), "mcpg_sk_xyz");

        // A bare anchor is not key material.
        let (url, key) = split_fragment("https://c.example/c/abc#section");
        assert_eq!(url, "https://c.example/c/abc");
        assert!(key.is_none());

        // Unknown params are ignored; the split is on the FIRST `=`.
        let (_, key) = split_fragment("https://c.example/c/abc#z=1&k=mcpg_sk_a=b&y=2");
        assert_eq!(key.unwrap().expose(), "mcpg_sk_a=b");

        // No fragment at all.
        let (url, key) = split_fragment("https://c.example/c/abc");
        assert_eq!(url, "https://c.example/c/abc");
        assert!(key.is_none());
    }

    #[test]
    fn redaction_masks_only_the_key_param() {
        assert_eq!(
            redacted_spec("https://c.example/c/abc#k=mcpg_sk_secret&v=2"),
            "https://c.example/c/abc#k=***&v=2"
        );
        // Nothing to mask leaves the value alone.
        assert_eq!(
            redacted_spec("https://c.example/c/abc#overview"),
            "https://c.example/c/abc#overview"
        );
        assert_eq!(
            redacted_spec("https://c.example/c/abc"),
            "https://c.example/c/abc"
        );
    }

    /// The vector the browser generated, opened by the code the gateway boots
    /// with.
    ///
    /// Every other test in this file and in `source.rs` seals with this crate's
    /// own helpers and opens with this crate's own code, which is
    /// self-consistent by construction and proves nothing about the publisher.
    /// This is the one that crosses the boundary. If the key derivation, the
    /// AAD, the secret alphabet, the base64 variant, or the AEAD parameters
    /// drift on either side, one of the two suites fails instead of a user's
    /// boot.
    ///
    /// Regenerate with `node apps/cloud-config/scripts/crypto-vector.mjs
    /// --generate` — and only when the construction itself changes, because a
    /// new vector is a wire break rather than a refresh.
    const VECTOR: &str = include_str!("testdata/config-enc-v1-vector.json");

    #[derive(serde::Deserialize)]
    struct Vector {
        construction: String,
        secret: String,
        id: String,
        version: u64,
        expires_at: i64,
        one_time_read: bool,
        kdf: String,
        kdf_salt_b64: String,
        nonce_b64: String,
        aad: String,
        ciphertext_b64: String,
        yaml: String,
        plaintext_name: String,
    }

    fn vector() -> Vector {
        serde_json::from_str(VECTOR).expect("the committed vector is JSON")
    }

    #[test]
    fn the_browser_s_vector_opens_with_the_gateway_s_code() {
        let v = vector();
        assert_eq!(v.construction, CONSTRUCTION);

        let payload = EncryptedPayload {
            id: v.id.clone(),
            version: v.version,
            expires_at: v.expires_at,
            one_time_read: v.one_time_read,
            kdf: v.kdf.clone(),
            kdf_salt: decode_b64("kdf_salt", &v.kdf_salt_b64).unwrap(),
            nonce: decode_b64("nonce", &v.nonce_b64).unwrap(),
            ciphertext: decode_b64("ct", &v.ciphertext_b64).unwrap(),
            served_aad: Some(v.aad.clone()),
        };
        // Built independently here, then compared: the vector's own string is
        // what the browser produced.
        assert_eq!(payload.aad(), v.aad);

        let secret = parse_secret(&v.secret).expect("the vector's secret parses");
        // One second before the authenticated expiry, so the vector does not
        // start failing when the wall clock passes it.
        let opened = open(&payload, &secret, v.expires_at - 1).expect("the vector decrypts");
        assert_eq!(opened.yaml, v.yaml);
        assert_eq!(opened.id, v.id);
        assert_eq!(opened.version, v.version);
        assert_eq!(opened.name.as_deref(), Some(v.plaintext_name.as_str()));
    }

    #[test]
    fn the_vector_stops_opening_when_a_bound_field_moves() {
        // Guards the vector against passing under a construction that ignores
        // half of what it is supposed to authenticate.
        let v = vector();
        let base = || EncryptedPayload {
            id: v.id.clone(),
            version: v.version,
            expires_at: v.expires_at,
            one_time_read: v.one_time_read,
            kdf: v.kdf.clone(),
            kdf_salt: decode_b64("kdf_salt", &v.kdf_salt_b64).unwrap(),
            nonce: decode_b64("nonce", &v.nonce_b64).unwrap(),
            ciphertext: decode_b64("ct", &v.ciphertext_b64).unwrap(),
            // Dropped: the served string would disagree first and mask the
            // question this test is asking of the tag itself.
            served_aad: None,
        };
        let secret = parse_secret(&v.secret).unwrap();
        let now = v.expires_at - 1;

        let mut moved_expiry = base();
        moved_expiry.expires_at = v.expires_at + 3600;
        assert!(matches!(
            open(&moved_expiry, &secret, now),
            Err(DecryptFailure::WrongSecret { .. })
        ));

        let mut rewound = base();
        rewound.version = v.version - 1;
        assert!(matches!(
            open(&rewound, &secret, now),
            Err(DecryptFailure::WrongSecret { .. })
        ));

        let mut flipped = base();
        flipped.one_time_read = !v.one_time_read;
        assert!(matches!(
            open(&flipped, &secret, now),
            Err(DecryptFailure::WrongSecret { .. })
        ));

        let mut moved = base();
        moved.id = "1a2b3c4d5e6f7g8h9j0kmnpqrs".to_owned();
        assert!(matches!(
            open(&moved, &secret, now),
            Err(DecryptFailure::WrongSecret { .. })
        ));

        // And the expiry is enforced after decryption, not just bound into it.
        assert!(matches!(
            open(&base(), &secret, v.expires_at + 1),
            Err(DecryptFailure::Expired { .. })
        ));
    }

    #[test]
    fn contradictory_env_secret_sources_are_a_boot_error() {
        assert!(reconcile_env_secret(None, None).unwrap().is_none());
        // Same value twice is not a contradiction.
        let agreed = reconcile_env_secret(Some("mcpg_sk_a".into()), Some("mcpg_sk_a".into()))
            .unwrap()
            .unwrap();
        assert_eq!(agreed.expose(), "mcpg_sk_a");
        // The file form wins when only it is set.
        assert_eq!(
            reconcile_env_secret(Some("mcpg_sk_file".into()), None)
                .unwrap()
                .unwrap()
                .expose(),
            "mcpg_sk_file"
        );
        let err = reconcile_env_secret(Some("mcpg_sk_a".into()), Some("mcpg_sk_b".into()))
            .unwrap_err()
            .to_string();
        assert!(
            err.contains(SECRET_FILE_ENV) && err.contains(SECRET_ENV),
            "{err}"
        );
    }
}
