//! CLI extension dispatch — kubectl-style plugin delegation.
//!
//! When `mcpg plugin <subcommand> [args...]` is invoked, the gateway delegates
//! to an external `mcpg-plugin` binary found on `$PATH`. This follows the
//! kubectl plugin convention:
//!
//! - `mcpg plugin pack ...`    → `mcpg-plugin pack ...`
//! - `mcpg plugin sign ...`    → `mcpg-plugin sign ...`
//! - `mcpg plugin push ...`    → `mcpg-plugin push ...`
//! - `mcpg plugin list`        → `mcpg-plugin list`
//!
//! The `mcpg-plugin` CLI is scoped to artifact file
//! management. Developer tooling (compilation,
//! key generation, scaffolding, release automation) is handled by each
//! plugin project's own toolchain, not via this dispatch path.
//!
//! The gateway passes through all environment variables, ensuring `MCPG_CONFIG`,
//! `MCPG_PLUGIN_DIR`, and other operator-configured values are visible to the
//! plugin CLI tool.
//!
//! If `mcpg-plugin` is not installed, a helpful error message is printed.

use std::path::{Path, PathBuf};
use std::process::Command;

/// Extension binary name that must be on `$PATH`.
const PLUGIN_CLI_BINARY: &str = "mcpg-plugin";

/// Tempdir guard returned by [`prepare_dev_mode`]. Owns the
/// generated dev-config file (and any sibling descriptor copies);
/// dropping it removes the on-disk artefacts at process exit. The
/// gateway's normal config-load path reads the file path from
/// `MCPG_CONFIG` before this guard drops, so the data lives long
/// enough for boot.
pub struct DevModeGuard {
    _tempdir: tempfile::TempDir,
}

/// Prepare `mcpg dev [--plugin <path> ...]` mode (the local dev
/// loader). Synthesises a minimal AppConfig YAML pointing at each
/// supplied artifact, writes it to a tempdir, and layers it onto
/// the operator's `MCPG_CONFIG` env var so the normal boot path
/// loads it like any other config.
///
/// Each `--plugin <path>` arg adds one `plugins[]` entry. The
/// plugin's class / id / runtime are read from the matching
/// `plugin.yaml` (sibling to the artifact, or
/// `<artifact_stem>.plugin.yaml` override). The artifact path is
/// embedded as a `path:` source so the gateway's dynamic loader
/// dlopens it directly — no OCI pull, no packaging step.
pub fn prepare_dev_mode(args: &[String]) -> anyhow::Result<DevModeGuard> {
    let mut plugin_paths: Vec<PathBuf> = Vec::new();
    let mut i = 0;
    while i < args.len() {
        match args[i].as_str() {
            "--plugin" => {
                let p = args
                    .get(i + 1)
                    .ok_or_else(|| anyhow::anyhow!("--plugin requires a path"))?;
                plugin_paths.push(PathBuf::from(p));
                i += 2;
            }
            "--stdio" => {
                // Handled by main.rs after build; skip here.
                i += 1;
            }
            "--help" | "-h" => {
                print_dev_help();
                std::process::exit(0);
            }
            unknown => {
                anyhow::bail!(
                    "unknown `mcpg dev` flag: {unknown}. Run `mcpg dev --help` for usage."
                );
            }
        }
    }

    if plugin_paths.is_empty() {
        print_dev_help();
        anyhow::bail!("`mcpg dev` requires at least one --plugin <path>");
    }

    // Materialise a YAML snippet that adds the requested plugins
    // to whatever the operator already has loaded. The base config
    // (transports, server, etc.) comes from the operator's existing
    // MCPG_CONFIG; this file only adds `plugins:` entries.
    let mut yaml = String::from(
        "# Auto-generated by `mcpg dev` (local dev loader).\n\
         # Loaded as a `MCPG_CONFIG` layered overlay so existing\n\
         # operator config (server, transports, observability …)\n\
         # is preserved; only `plugins:` is appended.\n\
         plugins:\n",
    );
    for path in &plugin_paths {
        let abs = path
            .canonicalize()
            .map_err(|e| anyhow::anyhow!("canonicalize {}: {e}", path.display()))?;
        let descriptor_path = find_sibling_descriptor(&abs)?;
        let descriptor_text = std::fs::read_to_string(&descriptor_path).map_err(|e| {
            anyhow::anyhow!(
                "reading descriptor {} for {}: {e}",
                descriptor_path.display(),
                abs.display()
            )
        })?;
        let descriptor: serde_yaml::Value = serde_yaml::from_str(&descriptor_text)
            .map_err(|e| anyhow::anyhow!("parse {}: {e}", descriptor_path.display()))?;
        let id = descriptor
            .get("id")
            .and_then(|v| v.as_str())
            .ok_or_else(|| {
                anyhow::anyhow!("descriptor {} missing `id`", descriptor_path.display())
            })?;
        let class = descriptor
            .get("class")
            .and_then(|v| v.as_str())
            .ok_or_else(|| {
                anyhow::anyhow!("descriptor {} missing `class`", descriptor_path.display())
            })?;
        yaml.push_str(&format!(
            "  - id: {id}\n    class: {class}\n    kind: native\n    source:\n      type: path\n      path: {}\n",
            abs.display()
        ));
    }

    let tempdir = tempfile::Builder::new()
        .prefix("mcpg-dev-")
        .tempdir()
        .map_err(|e| anyhow::anyhow!("create dev-mode tempdir: {e}"))?;
    let config_path = tempdir.path().join("dev-plugins.yaml");
    std::fs::write(&config_path, &yaml)
        .map_err(|e| anyhow::anyhow!("write {}: {e}", config_path.display()))?;

    // Layer onto the existing `MCPG_CONFIG`. Empty base → just our
    // file; non-empty → join with the platform path separator so
    // the normal `split_paths` parsing finds both.
    let new_config = match std::env::var_os("MCPG_CONFIG") {
        Some(existing) if !existing.is_empty() => {
            let mut paths: Vec<std::ffi::OsString> = std::env::split_paths(&existing)
                .map(|p| p.into_os_string())
                .collect();
            paths.push(config_path.clone().into_os_string());
            std::env::join_paths(paths)
                .map_err(|e| anyhow::anyhow!("join MCPG_CONFIG paths: {e}"))?
        }
        _ => config_path.clone().into_os_string(),
    };
    // SAFETY: we're in single-threaded `main()` before tokio
    // touches env vars; this matches the pre-existing
    // `MCPG_CONFIG` handling above.
    unsafe {
        std::env::set_var("MCPG_CONFIG", &new_config);
    }

    eprintln!(
        "mcpg dev: loaded {} plugin(s) via {} (layered onto MCPG_CONFIG)",
        plugin_paths.len(),
        config_path.display()
    );

    Ok(DevModeGuard { _tempdir: tempdir })
}

/// Locate the plugin descriptor sibling to an artifact path. Tries
/// `<artifact_dir>/plugin.yaml` first (the convention `mcpg plugin
/// new` scaffolds), then `<artifact_stem>.plugin.yaml` (so authors
/// can ship multiple distinct artifacts in one dir).
fn find_sibling_descriptor(artifact: &Path) -> anyhow::Result<PathBuf> {
    let dir = artifact
        .parent()
        .ok_or_else(|| anyhow::anyhow!("artifact path has no parent: {}", artifact.display()))?;

    let candidates = [
        dir.join("plugin.yaml"),
        dir.join(format!(
            "{}.plugin.yaml",
            artifact
                .file_stem()
                .and_then(|s| s.to_str())
                .unwrap_or("plugin")
        )),
        // For cargo-built cdylibs, the scaffolded `plugin.yaml`
        // lives at the crate root, not next to the
        // `target/release/lib*.so` artifact. Walk upward looking
        // for a `Cargo.toml` sibling-of-`plugin.yaml`.
        dir.join("../../plugin.yaml"),
        dir.join("../../../plugin.yaml"),
    ];
    for candidate in &candidates {
        if candidate.is_file() {
            return Ok(candidate
                .canonicalize()
                .unwrap_or_else(|_| candidate.clone()));
        }
    }
    anyhow::bail!(
        "no plugin.yaml found for {} (tried sibling + crate-root). \
         Use `mcpg plugin new` to scaffold one, or copy your descriptor next to the artifact.",
        artifact.display()
    )
}

fn print_dev_help() {
    eprintln!(
        "Usage: mcpg dev --plugin <artifact-path> [--plugin <path>] [--stdio]\n\
         \n\
         Run the gateway in local-dev mode with one or more path-loaded\n\
         plugins. Each --plugin entry is added to\n\
         the in-memory `plugins[]` config; the gateway's normal\n\
         MCPG_CONFIG continues to apply for transports, server, etc.\n\
         \n\
         The plugin descriptor (`plugin.yaml`) is read from:\n\
         \n  1. <artifact-parent>/plugin.yaml         (scaffolder convention)\n\
         \n  2. <artifact-stem>.plugin.yaml           (multi-artifact dir)\n\
         \n  3. <artifact-parent>/../../plugin.yaml   (cargo target/release/…)\n\
         \n\
         Useful loop:\n\
         \n  mcpg plugin new --kind tool_gate --name my-gate\n\
         \n  cd mcpg-plugin-tool-gate-my-gate && cargo build --release\n\
         \n  mcpg dev --plugin target/release/libmcpg_plugin_tool_gate_my_gate.so\n"
    );
}

/// Dispatch a `mcpg plugin <args>` invocation to the external `mcpg-plugin` binary.
///
/// Returns `Ok(())` if the plugin command executed successfully (exit code 0).
/// Returns an error if the binary is not found or exits with a non-zero code.
pub fn dispatch_plugin_command(args: &[String]) -> anyhow::Result<()> {
    if args.is_empty() {
        print_plugin_help();
        return Ok(());
    }

    let binary_path = match locate_binary(PLUGIN_CLI_BINARY) {
        Some(path) => path,
        None => {
            print_plugins_not_installed();
            std::process::exit(1);
        }
    };

    let status = Command::new(&binary_path)
        .args(args)
        .stdin(std::process::Stdio::inherit())
        .stdout(std::process::Stdio::inherit())
        .stderr(std::process::Stdio::inherit())
        .status();

    match status {
        Ok(exit_status) => {
            if exit_status.success() {
                Ok(())
            } else {
                let code = exit_status.code().unwrap_or(1);
                std::process::exit(code);
            }
        }
        Err(e) => {
            eprintln!("error: failed to execute '{}': {}", binary_path, e);
            std::process::exit(1);
        }
    }
}

/// Print help when `mcpg plugin` is called without arguments. The command
/// list is only shown when the delegate binary is actually installed —
/// advertising commands that cannot run is misleading.
fn print_plugin_help() {
    if locate_binary(PLUGIN_CLI_BINARY).is_none() {
        print_plugins_not_installed();
        return;
    }
    eprintln!(
        "mcpg plugin — MCPG plugin management\n\
         \n\
         Usage:\n\
         \n  mcpg plugin <command> [options]\n\
         \n\
         Commands (provided by mcpg-plugin):\n\
         \n  new        Scaffold a new plugin crate\
         \n  pack       Bundle a descriptor + artifact (+ signature) into a package\
         \n  unpack     Extract a packaged plugin\
         \n  sign       Create an Ed25519 detached signature\
         \n  hash       Compute the SHA-256 integrity hash\
         \n  verify     Verify a plugin artifact's hash/signature\
         \n  list       List plugin artifacts in a directory\
         \n  push       Publish a package to an OCI registry\
         \n  pull       Fetch a package from an OCI registry\
         \n  test       Run a package against a mock gateway\
         \n  cache      Manage the local OCI unpack cache\n"
    );
}

/// Explain that the `mcpg-plugin` delegate binary is missing and how to get it.
fn print_plugins_not_installed() {
    eprintln!(
        "error: '{PLUGIN_CLI_BINARY}' is not installed or not on PATH.\n\n\
         The mcpg plugin CLI extension is a separate tool for packing,\n\
         signing, pushing, and managing MCPG plugin artifacts.\n\n\
         Install it from the workspace source (the crate is publish=false,\n\
         so it is not on crates.io):\n\
         \n  cargo install --path apps/plugin\n\n\
         Or build it without installing:\n\
         \n  cargo build -p mcpg-plugin \n",
    );
}

/// Find a binary on `$PATH` and return its full path.
fn which_binary(name: &str) -> Option<String> {
    let path_var = std::env::var("PATH").unwrap_or_default();
    for dir in path_var.split(':') {
        let candidate = std::path::Path::new(dir).join(name);
        if candidate.is_file() {
            return Some(candidate.to_string_lossy().into_owned());
        }
    }
    None
}

/// Locate a sibling `mcpg-*` binary: first on `$PATH`, then in the directory of
/// the running `mcpg` executable. The fallback lets a colocated install (a
/// release tarball extracted somewhere off `$PATH`, or `./mcpg` run in place)
/// find its siblings without the user having to put the dir on `$PATH`.
pub fn locate_binary(name: &str) -> Option<String> {
    if let Some(p) = which_binary(name) {
        return Some(p);
    }
    let exe_dir = std::env::current_exe().ok()?;
    let candidate = exe_dir.parent()?.join(name);
    candidate
        .is_file()
        .then(|| candidate.to_string_lossy().into_owned())
}

/// True when the named sibling binary is installed (on `$PATH` or next to the
/// running `mcpg` executable). Help output uses this to avoid advertising
/// subcommands whose delegate binary cannot actually run.
fn sibling_available(name: &str) -> bool {
    locate_binary(name).is_some()
}

/// True when `arg` is a bare subcommand token rather than a flag. The gateway
/// boot path takes no positional argument (config comes from `MCPG_CONFIG`; the
/// rest are `--flags`), so any leading bare word is an extension subcommand.
pub fn is_subcommand_word(arg: &str) -> bool {
    !arg.is_empty() && !arg.starts_with('-')
}

/// Whether the CLI args request stdio transport (`--stdio`). This flag
/// overrides the configured `server.transport` after boot.
pub fn stdio_requested(args: &[String]) -> bool {
    args.iter().any(|a| a == "--stdio")
}

/// Dispatch a bare-word subcommand to its sibling `mcpg-*` binary,
/// kubectl-style: `mcpg <name> [args]` → `mcpg-<name> [args]` (config, cp,
/// cloud, admin, …).
///
/// All environment (incl. `MCPG_CONFIG`) and stdio are inherited; the child's
/// exit code is propagated. An unknown subcommand whose binary isn't installed
/// produces a helpful error rather than silently booting the gateway.
pub fn dispatch_subcommand(name: &str, args: &[String]) -> anyhow::Result<()> {
    exec_sibling(
        &format!("mcpg-{}", subcommand_binary_suffix(name)),
        args,
        name,
    )
}

/// The sibling-binary suffix for a subcommand word. Identity for everything
/// except the retained `cp` alias, which the control-plane binary answered
/// under before it was renamed to `mcpg-control-plane`.
pub fn subcommand_binary_suffix(name: &str) -> &str {
    match name {
        "cp" => "control-plane",
        other => other,
    }
}

/// Locate `binary` (PATH or sibling-of-`mcpg`) and exec it with `args`,
/// inheriting stdio and propagating the exit code. `label` names the `mcpg`
/// subcommand for error messages.
fn exec_sibling(binary: &str, args: &[String], label: &str) -> anyhow::Result<()> {
    let binary_path = match locate_binary(binary) {
        Some(path) => path,
        None => {
            eprintln!(
                "error: '{binary}' is not installed or not on PATH.\n\n\
                 `mcpg {label}` delegates to the sibling `{binary}` binary, which\n\
                 ships in the mcpg toolchain alongside `mcpg`. Install it with the\n\
                 installer (each binary is its own release artifact):\n\
                 \n  curl -fsSL https://raw.githubusercontent.com/mcpg-dev/source-code/main/install.sh | sh -s -- --bin {binary}\n\
                 \nor build from the workspace source:\n\
                 \n  cargo build -p mcpg -p mcpg-config          # mcpg + mcpg-config\n\
                 \n  cargo build -p mcpg-control-plane-server    # mcpg-control-plane\n\
                 \n  cargo build -p mcpg-cloud -p mcpg-admin     # cloud CLIs\n",
            );
            std::process::exit(1);
        }
    };

    let status = Command::new(&binary_path)
        .args(args)
        .stdin(std::process::Stdio::inherit())
        .stdout(std::process::Stdio::inherit())
        .stderr(std::process::Stdio::inherit())
        .status();

    match status {
        Ok(exit_status) if exit_status.success() => Ok(()),
        Ok(exit_status) => std::process::exit(exit_status.code().unwrap_or(1)),
        Err(e) => {
            eprintln!("error: failed to execute '{binary_path}': {e}");
            std::process::exit(1);
        }
    }
}

/// Print top-level `mcpg` usage: the subcommand groups plus the gateway-boot
/// default. Shown for `mcpg help` / `mcpg --help`. Toolchain groups are only
/// listed when their delegate `mcpg-*` binary is installed; a footnote points
/// at the full toolchain otherwise.
pub fn print_top_help() {
    let config = sibling_available("mcpg-config");
    let cp = sibling_available("mcpg-control-plane");
    let cloud = sibling_available("mcpg-cloud");
    let admin = sibling_available("mcpg-admin");
    let plugins = sibling_available(PLUGIN_CLI_BINARY);
    let inspector = sibling_available("mcpg-inspector");

    let mut out = String::from(
        "mcpg — the MCP Gateway, and the front door to its toolchain\n\
         \n\
         Usage:\n\
         \n  mcpg                       Boot the gateway (config from MCPG_CONFIG)\n\
         \n  mcpg --stdio               Boot the gateway on the stdio transport\n\
         \n  mcpg --tunnel [wss-url]    Serve through a relay tunnel instead of a\n\
         \n                             public port (defaults to the MCPG Cloud\n\
         \n                             relay; pass a URL for a self-hosted relay)\n\
         \n  mcpg <command> [args...]   Run a toolchain subcommand (below)\n\
         \n\
         Commands (delegate to sibling mcpg-* binaries):\n",
    );
    if config {
        out.push_str(
            "\n  config <sub>   Generate / validate / explain configuration (→ mcpg-config)\
             \n                   init, check, doc, explain, schema, secrets, wiring",
        );
    }
    if cp {
        out.push_str(
            "\n  control-plane <sub>  The control plane: serve / enroll / status\
             \n                   (→ mcpg-control-plane; `mcpg cp …` is an alias)\
             \n                   e.g. `mcpg control-plane serve --dev`",
        );
    }
    if cloud {
        out.push_str(
            "\n  cloud <sub>    mcpg.cloud tenant CLI (→ mcpg-cloud)\
             \n                   e.g. `mcpg cloud publish --name edge --config gw.yaml`",
        );
    }
    if admin {
        out.push_str("\n  admin <sub>    mcpg.cloud platform-operator CLI (→ mcpg-admin)");
    }
    if plugins {
        out.push_str("\n  plugin <sub>   Manage plugin artifacts (→ mcpg-plugin)");
    }
    if inspector {
        out.push_str(
            "\n  inspector <sub>  Inspect MCP servers: serve / list / call / read\
             \n                   (→ mcpg-inspector; `mcpg --inspector` supervises\
             \n                   one against this gateway)",
        );
    }
    out.push_str("\n  status         This box: gateway, agent pairing, local control plane");
    out.push_str("\n  dev            Run the gateway with path-loaded plugins (local dev)\n");
    if !config || !cp || !cloud || !admin || !plugins || !inspector {
        out.push_str(
            "\nSome toolchain commands are not shown because their mcpg-* binary is\n\
             not installed (looked on PATH and next to `mcpg`). Install the full\n\
             mcpg toolchain, or build from the workspace source:\n\
             \n  cargo build -p mcpg -p mcpg-config          # mcpg + mcpg-config\n\
             \n  cargo build -p mcpg-plugin                  # mcpg plugin <sub>\n\
             \n  cargo build -p mcpg-control-plane-server    # mcpg control-plane <sub>\n\
             \n  cargo build -p mcpg-cloud                   # mcpg cloud <sub>\n\
             \n  cargo build -p mcpg-admin                   # mcpg admin <sub>\n",
        );
    }
    out.push_str("\nRun `mcpg <command> --help` for a command's own usage.\n");
    eprintln!("{out}");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn which_binary_finds_common_tools() {
        // `ls` should exist on any Linux system
        let result = which_binary("ls");
        assert!(result.is_some(), "expected to find 'ls' on PATH");
    }

    #[test]
    fn which_binary_returns_none_for_nonexistent() {
        let result = which_binary("this-definitely-does-not-exist-8675309");
        assert!(result.is_none());
    }

    #[test]
    fn plugin_cli_binary_name_is_correct() {
        assert_eq!(PLUGIN_CLI_BINARY, "mcpg-plugin");
    }

    #[test]
    fn subcommand_word_accepts_bare_tokens_rejects_flags() {
        assert!(is_subcommand_word("config"));
        assert!(is_subcommand_word("ctl"));
        assert!(is_subcommand_word("plugin"));
        assert!(!is_subcommand_word("--stdio"));
        assert!(!is_subcommand_word("-h"));
        assert!(!is_subcommand_word("--config"));
        assert!(!is_subcommand_word(""));
    }

    #[test]
    fn subcommand_words_map_to_sibling_binaries() {
        // `mcpg config …` → `mcpg-config` — one uniform rule since the
        // per-subcommand config bins merged.
        for word in ["config", "cloud", "admin", "control-plane"] {
            assert_eq!(word, subcommand_binary_suffix(word));
        }
        // `cp` is the retained alias for the renamed control-plane binary.
        assert_eq!("control-plane", subcommand_binary_suffix("cp"));
    }

    #[test]
    fn locate_binary_finds_path_entries() {
        // `locate_binary` falls back to the exe dir but must still find PATH tools.
        assert!(locate_binary("ls").is_some());
        assert!(locate_binary("this-definitely-does-not-exist-8675309").is_none());
    }

    #[test]
    fn sibling_available_tracks_binary_presence() {
        assert!(sibling_available("ls"));
        assert!(!sibling_available("mcpg-this-does-not-exist-8675309"));
    }
}
